import styles from './page.module.scss';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Suspense } from 'react';
import '@/styles/global.scss';

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <Suspense fallback={<div>로딩 중...</div>}>
          <div className={styles.layout}>{children}</div>
        </Suspense>
      </body>
    </html>
  );
};

export default RootLayout;
