import styles from './page.module.scss';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { ToastProvider } from '@/Context/ToastProvider';
import '@/styles/global.scss';

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) => {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <ToastProvider>
          <div className={styles.layout}>{children}</div>
        </ToastProvider>
        {modal}
        <div id="portal"></div>
      </body>
    </html>
  );
};

export default RootLayout;
