import styles from './page.module.scss';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { cookies } from 'next/headers';
import QueryProvider from '@/providers/QueryProvider';
import '@/styles/global.scss';
import { setServerToken } from '@/utils/tokenCache';

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  modal: React.ReactNode;
}

const RootLayout = async ({ children, modal }: Readonly<RootLayoutProps>) => {
  const cookieStore = await cookies();
  const token = cookieStore.get('accessToken')?.value || '';
  setServerToken(token);

  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <QueryProvider>
          <div className={styles.layout}>{children}</div>
          {modal}
        </QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
